### ISSUE TITLE
DSL Impovements: introduce namespaces

### ISSUE THREAD

**Issue by bugzmanov** [griddynamics/OpenGenesis#737]
Background: Currently context access and variables live in the same context, thus making it hard to locate where did value come from

In order to be able to read dsl script easilty, genesis dsl engine should support following namespaces:
- $vars for variables
- $context ($exports? ) - for context access.

example: access variable foo 

```
variables {
  variable ("foo").description("Provide foo")
}
steps {
  step1 {
       value = $vars.foo
   }
}
```

[More complex sample](https://gist.github.com/3df8edd6a382efbeae45)

**Comment by bugzmanov** [comment]
isn't this implemented already?

**Comment by ddurnev** [comment]
It seems we have both $vars and $context namespaces. No other namespaces are necessary?

**Comment by bugzmanov** [comment]
as far as i can see from issue description, it is enough for now
