### ISSUE TITLE
Predefined databag templates

### ISSUE THREAD

**Issue by bugzmanov** [griddynamics/OpenGenesis#745]
Background: Most projects have predefined set of properties and it's error prone to enter keys every time manually.
This especially is true for databags having same tags. For instance it's unlikely that in the same project several database configurations will have different key set.

In order to improve project admins experience, genesis should support "databag template" - predefined set of keys, that user should be able to select during databag creation process.

Note: probably the same approach should be applied to env configuration properties.

**Comment by ddurnev** [comment]
Implemented by S. Reentenko.
